In [1]:
import numpy as np

In [2]:
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]

In [3]:
sales_array = np.array(sales)
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [4]:
print(f'ndim: {sales_array.ndim})')
print(f'shape: {sales_array.shape})')
print(f'size: {sales_array.size})')
print(f'dtype: {sales_array.dtype})')

ndim: 1)
shape: (10,))
size: 10)
dtype: int32)


In [5]:
#Array excercise
my_list = [x * 10 for x in range(1,11)]
my_list_array = np.array(my_list)
my_list_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [6]:
print(f'ndim: {my_list_array.ndim})')
print(f'shape: {my_list_array.shape})')
print(f'size: {my_list_array.size})')
print(f'dtype: {my_list_array.dtype})')

ndim: 1)
shape: (10,))
size: 10)
dtype: int32)


In [7]:
# Array Creation
np.ones(4,)

array([1., 1., 1., 1.])

In [8]:
np.zeros((2, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [11]:
np.arange(1, 9, 2).reshape(2,2)

array([[1, 3],
       [5, 7]])

In [12]:
# Random number arrays
from numpy.random import default_rng
rng = default_rng(12345)
random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [13]:
rng = default_rng(12345)
mean, stddev = 5, 1
random_normal = rng.normal(mean, stddev, size=10)
random_normal

array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

In [14]:
#Array operations
import numpy as np
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]

sales_array = np.array(sales)
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [15]:
sales_array + 2

array([[   2,    7,  157,    2,  520],
       [   2, 1829,  618,  319,  327]])

In [16]:
quantity = sales_array[0, :]
quantity

array([  0,   5, 155,   0, 518])

In [17]:
price = sales_array[1, :]
price

array([   0, 1827,  616,  317,  325])

In [18]:
quantity * price

array([     0,   9135,  95480,      0, 168350])

In [19]:
import numpy as np
prices  = np.array([5.99, 6.99, 22.99, 99.99, 4.99, 49.99])

In [20]:
total = prices + 5
total

array([ 10.99,  11.99,  27.99, 104.99,   9.99,  54.99])

In [21]:
import numpy as np


random_array = np.random.rand(12)

discount_pct = random_array[:6].reshape(6)   
pct_owed = 1 - discount_pct
final_owed = total + pct_owed
final_owed.round(2)

array([ 11.29,  12.84,  28.73, 105.96,  10.66,  55.93])

In [22]:
###filtering arrays

In [23]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [24]:
sales_array != 0

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True,  True]])

In [25]:
sales_array[sales_array != 0]

array([   5,  155,  518, 1827,  616,  317,  325])

In [26]:
# multiple logical tests

In [27]:
sales_array[(sales_array > 100) & (sales_array < 500)]

array([155, 317, 325])

In [28]:
###PRO TIP: Store complex
#filtering criteria in a variable
#(known as a Boolean mask)

mask = (sales_array > 100) & (sales_array < 500)
sales_array[mask]

array([155, 317, 325])

In [29]:
##filter arrays based on values in other arrays

In [30]:
product_list = ['fruits', 'vegetable', 'cereal', 'dairy', 'eggs', 'meat','potatoes']
product_array = np.array(product_list)
product_array

array(['fruits', 'vegetable', 'cereal', 'dairy', 'eggs', 'meat',
       'potatoes'], dtype='<U9')

In [31]:
product_array[sales_array > 0]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
print(product_array.shape)
print(sales_array.shape)

In [ ]:
sales_array.shape

(2, 5)

In [32]:
sales_array[1] = 5

In [33]:
sales_array

array([[  0,   5, 155,   0, 518],
       [  5,   5,   5,   5,   5]])

In [34]:
sales_array[sales_array == 0] = 25

In [35]:
sales_array

array([[ 25,   5, 155,  25, 518],
       [  5,   5,   5,   5,   5]])

In [36]:
inventory_list = [12, 102, 18, 0, 0]

In [37]:
inventory_array = np.array(inventory_list)

In [38]:
inventory_array

array([ 12, 102,  18,   0,   0])

In [42]:
np.where(inventory_array <= 0, 'out_of_stock', 'in_stock')

array(['in_stock', 'in_stock', 'in_stock', 'out_of_stock', 'out_of_stock'],
      dtype='<U12')

In [41]:
product_list = ['fruits', 'vegetable', 'cereal', 'dairy', 'eggs']
product_array = np.array(product_list)
product_array

array(['fruits', 'vegetable', 'cereal', 'dairy', 'eggs'], dtype='<U9')

In [43]:
np.where(inventory_array <= 0, 'out_of_stock', product_array)

array(['fruits', 'vegetable', 'cereal', 'out_of_stock', 'out_of_stock'],
      dtype='<U12')