In [13]:
import numpy as np

In [14]:
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]

In [15]:
sales_array = np.array(sales)
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [16]:
print(f'ndim: {sales_array.ndim})')
print(f'shape: {sales_array.shape})')
print(f'size: {sales_array.size})')
print(f'dtype: {sales_array.dtype})')

ndim: 1)
shape: (10,))
size: 10)
dtype: int64)


In [17]:
#Array excercise
my_list = [x * 10 for x in range(1,11)]
my_list_array = np.array(my_list)
my_list_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [18]:
print(f'ndim: {my_list_array.ndim})')
print(f'shape: {my_list_array.shape})')
print(f'size: {my_list_array.size})')
print(f'dtype: {my_list_array.dtype})')

ndim: 1)
shape: (10,))
size: 10)
dtype: int64)


In [19]:
# Array Creation
np.ones(4,)

array([1., 1., 1., 1.])

In [20]:
np.zeros((2, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.linspace(0,100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [23]:
np.arange(1, 9, 2).reshape(2,2)

array([[1, 3],
       [5, 7]])

In [24]:
# Random number arrays
from numpy.random import default_rng
rng = default_rng(12345)
random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [25]:
rng = default_rng(12345)
mean, stddev = 5, 1
random_normal = rng.normal(mean, stddev, size=10)
random_normal

array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

In [26]:
#Array operations
import numpy as np
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]

sales_array = np.array(sales)
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [27]:
sales_array + 2

array([[   2,    7,  157,    2,  520],
       [   2, 1829,  618,  319,  327]])

In [28]:
quantity = sales_array[0, :]
quantity

array([  0,   5, 155,   0, 518])

In [29]:
price = sales_array[1, :]
price

array([   0, 1827,  616,  317,  325])

In [30]:
quantity * price

array([     0,   9135,  95480,      0, 168350])

In [31]:
import numpy as np
prices  = np.array([5.99, 6.99, 22.99, 99.99, 4.99, 49.99])

In [32]:
total = prices + 5
total

array([ 10.99,  11.99,  27.99, 104.99,   9.99,  54.99])

In [33]:
import numpy as np


random_array = np.random.rand(12)

discount_pct = random_array[:6].reshape(6)   
pct_owed = 1 - discount_pct
final_owed = total + pct_owed
final_owed.round(2)

array([ 11.29,  12.67,  28.54, 105.98,  10.16,  55.05])

In [34]:
###filtering arrays

In [35]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [36]:
sales_array != 0

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True,  True]])

In [37]:
sales_array[sales_array != 0]

array([   5,  155,  518, 1827,  616,  317,  325])

In [38]:
# multiple logical tests

In [39]:
sales_array[(sales_array > 100) & (sales_array < 500)]

array([155, 317, 325])

In [40]:
###PRO TIP: Store complex
#filtering criteria in a variable
#(known as a Boolean mask)

mask = (sales_array > 100) & (sales_array < 500)
sales_array[mask]

array([155, 317, 325])

In [41]:
##filter arrays based on values in other arrays

In [42]:
product_list = ['fruits', 'vegetable', 'cereal', 'dairy', 'eggs', 'meat','potatoes']
product_array = np.array(product_list)
product_array

array(['fruits', 'vegetable', 'cereal', 'dairy', 'eggs', 'meat',
       'potatoes'], dtype='<U9')

In [43]:
#product_array[sales_array > 0]

In [44]:
print(product_array.shape)
print(sales_array.shape)

(7,)
(2, 5)


In [45]:
sales_array.shape

(2, 5)

In [46]:
sales_array[1] = 5

In [47]:
sales_array

array([[  0,   5, 155,   0, 518],
       [  5,   5,   5,   5,   5]])

In [48]:
sales_array[sales_array == 0] = 25

In [49]:
sales_array

array([[ 25,   5, 155,  25, 518],
       [  5,   5,   5,   5,   5]])

In [50]:
inventory_list = [12, 102, 18, 0, 0]

In [51]:
inventory_array = np.array(inventory_list)

In [52]:
inventory_array

array([ 12, 102,  18,   0,   0])

In [53]:
np.where(inventory_array <= 0, 'out_of_stock', 'in_stock')

array(['in_stock', 'in_stock', 'in_stock', 'out_of_stock', 'out_of_stock'],
      dtype='<U12')

In [54]:
product_list = ['fruits', 'vegetable', 'cereal', 'dairy', 'eggs']
product_array = np.array(product_list)
product_array

array(['fruits', 'vegetable', 'cereal', 'dairy', 'eggs'], dtype='<U9')

In [55]:
np.where(inventory_array <= 0, 'out_of_stock', product_array)

array(['fruits', 'vegetable', 'cereal', 'out_of_stock', 'out_of_stock'],
      dtype='<U12')

In [56]:
sales_array

array([[ 25,   5, 155,  25, 518],
       [  5,   5,   5,   5,   5]])

In [57]:
print(f'The sum is: {sales_array.sum()}')
print(f'The min is: {sales_array.min()}')
print(f'The max is: {sales_array.max()}')
print(f'The mean is: {sales_array.mean()}')

The sum is: 753
The min is: 5
The max is: 518
The mean is: 75.3


In [58]:
print(f'The sum is aggregated across the rows: {sales_array.sum(axis=0)}')
print(f'The sum is aggregated across the columns: {sales_array.sum(axis=1)}')

The sum is aggregated across the rows: [ 30  10 160  30 523]
The sum is aggregated across the columns: [728  25]


In [59]:
np.unique(sales_array)

array([  5,  25, 155, 518])

In [60]:
np.sqrt(sales_array)

array([[ 5.        ,  2.23606798, 12.4498996 ,  5.        , 22.75961335],
       [ 2.23606798,  2.23606798,  2.23606798,  2.23606798,  2.23606798]])

In [61]:
sales_array.sort()
sales_array

array([[  5,  25,  25, 155, 518],
       [  5,   5,   5,   5,   5]])

In [62]:
sales_array.sort(axis=0)
sales_array

array([[  5,   5,   5,   5,   5],
       [  5,  25,  25, 155, 518]])

In [63]:
import pandas as pd
retail_df = pd.read_csv(r"C:\Users\TAJ\Desktop\python 101_\data\retail_2016_2017.csv").sample(1000, random_state=100)

In [64]:
retail_df

,id,date,store_nbr,family,sales,onpromotion
497061,2443005,2016-10-05,6,HOME AND KITCHEN I,31.000,0
562089,2508033,2016-11-11,30,AUTOMOTIVE,2.000,0
165783,2111727,2016-04-03,10,MEATS,278.173,0
531350,2477294,2016-10-25,18,HOME APPLIANCES,0.000,0
540362,2486306,2016-10-30,20,LAWN AND GARDEN,7.000,2
...,...,...,...,...,...,...
231385,2177329,2016-05-09,50,"LIQUOR,WINE,BEER",69.000,0
926789,2872733,2017-06-05,13,HOME APPLIANCES,0.000,0
513748,2459692,2016-10-15,24,BOOKS,6.000,0
72189,2018133,2016-02-10,34,HOME CARE,269.000,0


In [65]:
family_array = np.array(retail_df['family'])
family_array

array(['HOME AND KITCHEN I', 'AUTOMOTIVE', 'MEATS', 'HOME APPLIANCES',
       'LAWN AND GARDEN', 'PRODUCE', 'PREPARED FOODS', 'PRODUCE',
       'PREPARED FOODS', 'BEAUTY', 'EGGS', 'POULTRY', 'GROCERY II',
       'GROCERY I', 'CLEANING', 'POULTRY', 'BREAD/BAKERY', 'PET SUPPLIES',
       'HOME AND KITCHEN I', 'LAWN AND GARDEN', 'HOME AND KITCHEN I',
       'MEATS', 'HOME CARE', 'GROCERY I', 'PERSONAL CARE', 'BREAD/BAKERY',
       'HOME AND KITCHEN I', 'GROCERY II', 'EGGS',
       'SCHOOL AND OFFICE SUPPLIES', 'MAGAZINES', 'LADIESWEAR',
       'GROCERY I', 'BEAUTY', 'HOME APPLIANCES', 'CELEBRATION',
       'HARDWARE', 'MAGAZINES', 'MAGAZINES', 'CLEANING',
       'LIQUOR,WINE,BEER', 'MAGAZINES', 'SEAFOOD', 'BEAUTY',
       'CELEBRATION', 'PREPARED FOODS', 'HARDWARE', 'LAWN AND GARDEN',
       'PLAYERS AND ELECTRONICS', 'SCHOOL AND OFFICE SUPPLIES',
       'LAWN AND GARDEN', 'MEATS', 'BEAUTY', 'DAIRY', 'HOME APPLIANCES',
       'SEAFOOD', 'CLEANING', 'FROZEN FOODS', 'BEVERAGES', 'FROZEN FOO

In [66]:
sales_array = np.array(retail_df['sales'])
sales_array

array([3.10000000e+01, 2.00000000e+00, 2.78173000e+02, 0.00000000e+00,
       7.00000000e+00, 1.04171250e+04, 5.80670000e+01, 8.71078900e+03,
       7.68740000e+01, 5.00000000e+00, 2.91000000e+02, 9.08394000e+02,
       2.30000000e+01, 8.04500000e+03, 2.16000000e+03, 1.15283005e+02,
       0.00000000e+00, 6.00000000e+00, 9.00000000e+00, 2.80000000e+01,
       1.50000000e+01, 6.06000000e+01, 4.09000000e+02, 4.36400000e+03,
       1.23000000e+02, 5.49482000e+02, 1.10000000e+01, 1.70000000e+01,
       3.40000000e+01, 2.00000000e+00, 2.10000000e+01, 6.00000000e+01,
       1.43720000e+04, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 2.00000000e+00, 1.10000000e+01, 1.24900000e+03,
       3.10000000e+02, 3.00000000e+00, 2.55320000e+01, 2.00000000e+00,
       8.00000000e+00, 6.28050000e+01, 0.00000000e+00, 0.00000000e+00,
       1.40000000e+01, 0.00000000e+00, 5.00000000e+00, 5.22984000e+02,
       5.00000000e+00, 4.69000000e+02, 0.00000000e+00, 2.17320000e+01,
      

In [67]:
# sales_array.mean()
product_sales = sales_array[family_array == "PRODUCE"]
product_sales

array([10417.125,  8710.789,  1504.816,  1249.184,  1921.589,  7257.174,
        1416.474,  2810.283,  2049.904,   183.336,  7293.329,  7644.236,
        1363.99 ,   289.345,  1387.365,   537.085,   738.047,  1455.307,
        3239.463, 12900.818,   588.125,   784.407,   936.59 ,   358.007,
        1715.951])

In [68]:
product_sales[rng.random(25) < 0.5].mean()

np.float64(3076.3537692307696)

In [69]:
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]
sales_series = pd.Series(sales, name="Sales")
sales_series

0       0
1       5
2     155
3       0
4     518
5       0
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [70]:
sales_series.values

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [71]:
print(f'The values are : {sales_series.values}')
print(f'The index is : {sales_series.index}')
print(f'The names is : {sales_series.name}')
print(f'The datatype is : {sales_series.dtype}')

The values are : [   0    5  155    0  518    0 1827  616  317  325]
The index is : RangeIndex(start=0, stop=10, step=1)
The names is : Sales
The datatype is : int64


In [72]:
sales_series

0       0
1       5
2     155
3       0
4     518
5       0
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [73]:
sales_series.astype('bool')

0    False
1     True
2     True
3    False
4     True
5    False
6     True
7     True
8     True
9     True
Name: Sales, dtype: bool

In [74]:
sales_series.astype('float')

0       0.0
1       5.0
2     155.0
3       0.0
4     518.0
5       0.0
6    1827.0
7     616.0
8     317.0
9     325.0
Name: Sales, dtype: float64

In [75]:
# sales_series.astype('datetime64')
# ValueError: The 'datetime64' dtype has no unit. Please pass in 'datetime64[ns]' instead.

In [76]:
sales_series

0       0
1       5
2     155
3       0
4     518
5       0
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [77]:
sales_series.head()

0      0
1      5
2    155
3      0
4    518
Name: Sales, dtype: int64

In [78]:
sales_series.describe()

count      10.000000
mean      376.300000
std       557.759018
min         0.000000
25%         1.250000
50%       236.000000
75%       469.750000
max      1827.000000
Name: Sales, dtype: float64

In [79]:
sales_series.loc[1]

np.int64(5)

In [80]:
sales_series.iloc[2]

np.int64(155)

In [81]:
sales_series[sales_series > 10]

2     155
4     518
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [82]:
sales_series[sales_series > 100]

2     155
4     518
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [83]:
sales_series.head()

0      0
1      5
2    155
3      0
4    518
Name: Sales, dtype: int64

In [84]:
sales_series.shape

(10,)

In [85]:
sales_series.describe()

count      10.000000
mean      376.300000
std       557.759018
min         0.000000
25%         1.250000
50%       236.000000
75%       469.750000
max      1827.000000
Name: Sales, dtype: float64

In [86]:
df = sales_series[sales_series > 200]

In [87]:
df

4     518
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [88]:
sales_series

0       0
1       5
2     155
3       0
4     518
5       0
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [89]:
sales_series[2]

np.int64(155)

In [90]:
sales_series[2:5]

2    155
3      0
4    518
Name: Sales, dtype: int64

In [91]:

Sales = [0, 5,5,  155, 0, 518]
Items = ["coffee","coffee", "bananas", "tea", "coconut", "sugar" ]

In [92]:
Sales

[0, 5, 5, 155, 0, 518]

In [93]:
Items

['coffee', 'coffee', 'bananas', 'tea', 'coconut', 'sugar']

In [94]:
Sales_Series = pd.Series(Sales, index=Items, name="Sales")
Sales_Series

coffee       0
coffee       5
bananas      5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [95]:
Sales_Series['coffee']

coffee    0
coffee    5
Name: Sales, dtype: int64

In [96]:
Sales_Series['coffee':'sugar']

coffee       0
coffee       5
bananas      5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [97]:
Sales_Series.iloc[2:4]

bananas      5
tea        155
Name: Sales, dtype: int64

In [98]:
Sales_Series.loc["tea"]

np.int64(155)

In [99]:
Sales_Series.loc["tea":'sugar']

tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [100]:
Sales_Series.loc["tea"]

np.int64(155)

In [101]:
Sales_Series.loc["coffee"]

coffee    0
coffee    5
Name: Sales, dtype: int64

In [102]:
Sales_Series.reset_index()

,index,Sales
0,coffee,0
1,coffee,5
2,bananas,5
3,tea,155
4,coconut,0
5,sugar,518


In [103]:
Sales_Series.loc[Sales_Series > 0]

coffee       5
bananas      5
tea        155
sugar      518
Name: Sales, dtype: int64

In [104]:
mask = (Sales_Series > 0) & (Sales_Series == "tea")
Sales_Series.loc[mask]

Series([], Name: Sales, dtype: int64)

In [105]:
mask = (Sales_Series > 0) & (Sales_Series == "coffee")
Sales_Series.loc[mask]

Series([], Name: Sales, dtype: int64)

In [106]:
Sales_Series == 5

coffee     False
coffee      True
bananas     True
tea        False
coconut    False
sugar      False
Name: Sales, dtype: bool

In [107]:
Sales_Series.eq(5)

coffee     False
coffee      True
bananas     True
tea        False
coconut    False
sugar      False
Name: Sales, dtype: bool

In [108]:
Sales_Series.index.isin(["coffee","tea"])

array([ True,  True, False,  True, False, False])

In [109]:
~Sales_Series.index.isin(["coffee","tea"])

array([False, False,  True, False,  True,  True])

In [110]:
Sales_Series.sort_values()

coffee       0
coconut      0
bananas      5
coffee       5
tea        155
sugar      518
Name: Sales, dtype: int64

In [111]:
Sales_Series.sort_values(ascending=False)

sugar      518
tea        155
bananas      5
coffee       5
coffee       0
coconut      0
Name: Sales, dtype: int64

In [112]:
Sales_Series.sort_index()

bananas      5
coconut      0
coffee       0
coffee       5
sugar      518
tea        155
Name: Sales, dtype: int64

In [113]:
Sales_Series.sort_index(ascending=False)

tea        155
sugar      518
coffee       0
coffee       5
coconut      0
bananas      5
Name: Sales, dtype: int64

In [115]:
oil_df = pd.read_csv(r"C:\Users\TAJ\Desktop\python 101_\data\retail\oil.csv")
oil_df.head()

,date,dcoilwtico
0,2013-01-01,NaN
1,2013-01-02,93.14
2,2013-01-03,92.97
3,2013-01-04,93.12
4,2013-01-07,93.20


In [116]:
oil_df.describe()

,dcoilwtico
count,1175.000000
mean,67.714366
std,25.630476
min,26.190000
25%,46.405000
50%,53.190000
75%,95.660000
max,110.620000


In [118]:
oil_df.shape

(1218, 2)

In [119]:
oil_df.dtypes

date           object
dcoilwtico    float64
dtype: object