In [1]:
import numpy as np

In [13]:
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]

In [15]:
sales_array = np.array(sales)
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [17]:
print(f'ndim: {sales_array.ndim})')
print(f'shape: {sales_array.shape})')
print(f'size: {sales_array.size})')
print(f'dtype: {sales_array.dtype})')

ndim: 1)
shape: (10,))
size: 10)
dtype: int32)


In [21]:
#Array excercise
my_list = [x * 10 for x in range(1,11)]
my_list_array = np.array(my_list)
my_list_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [23]:
print(f'ndim: {my_list_array.ndim})')
print(f'shape: {my_list_array.shape})')
print(f'size: {my_list_array.size})')
print(f'dtype: {my_list_array.dtype})')

ndim: 1)
shape: (10,))
size: 10)
dtype: int32)


In [25]:
# Array Creation
np.ones(4,)

array([1., 1., 1., 1.])

In [27]:
np.zeros((2, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.linspace(0,100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [35]:
np.arange(1, 9, 2).reshape(2,2)

array([[1, 3],
       [5, 7]])

In [37]:
# Random number arrays
from numpy.random import default_rng
rng = default_rng(12345)
random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])